version: "3.8"

services:  
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
  
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - iot

networks:
  iot:

volumes:
  influxdb-data:
